name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, nightly, macos, win-msvc]
        include:
          - build: stable
            os: ubuntu-18.04
            rust: stable
          - build: nightly
            os: ubuntu-18.04
            rust: nightly
          - build: macos
            os: macOS-latest
            rust: stable
          - build: win-msvc
            os: windows-2019
            rust: stable
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: run test's
        run: cargo test --package env-watcher --lib test
      - name: exmaple snapshot
        run: cargo run --package env-watcher --example change_handler
      - name: exmaple change handler
        run: cargo run --package env-watcher --example snapshot
      - name: exmaple derive base
        run: cargo run --package env-watcher --example derive_base
      - name: exmaple derive snapshot
        run: cargo run --package env-watcher --example derive_snapshot